name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pdm
      - run: pdm install -G lint -G test
      - run: pdm run pytest tests/ -q
      - run: pdm run ruff check backon/
      - run: pdm build
      - run: pdm publish --repository pypi
