name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v5.5.0
        with:
          python-version: "3.12"
          cache: pip

      - run: pip install pdm

      - run: pdm install -G lint -G test

      - run: pdm run pytest tests/ -q

      - run: pdm run ruff check backon/

      - run: pdm run mypy backon/

  build:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v5.5.0
        with:
          python-version: "3.12"
          cache: pip

      - run: pip install pdm

      - run: pdm build

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Packages
          path: dist/*

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
      - uses: actions/download-artifact@95815c38cf0ffb484b702c4faba4891eef54c917 # v4.2.1
        with:
          name: Packages
          path: dist

      - uses: actions/attest-build-provenance@c074ebf1a1cf6c3d1b0ddc116f75866807e08688 # v2.2.3
        with:
          subject-path: "dist/*"

      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
